### ISSUE TITLE
feature request: xsm should restore window sizes and positions (geometry) on session restore

### ISSUE THREAD

**Issue by N0rbert** [nlpsuge/xsession-manager#23]
Thank you for your great project!

It would be really great if `xsm` will save and restore window sizes and positions (geometry). 
If I understand correctly, then the current master branch only saves the geometry, but can't restore it.

**Comment by nlpsuge** [comment]
> If I understand correctly, then the current master branch only saves the geometry, but can't restore it.

Yes, you are right.
I'm working on this. It will take some time to complish.

**Comment by nlpsuge** [comment]
Hi,

xsession-manager has support restoring window's geometry now.

You can upgrade to the latest version which is 1.0.4 via:
pip install --upgrade xsession-manager

Note that window's geometry will **NOT** restored **unless you save windows session firstly using latest version of `xsm`**.  Because `provider` field is missing in old saved session files, and I need it to detect which tool is used to restore geometry.

Feel free to report any issue :)

**Comment by N0rbert** [comment]
Thanks! 
It works.
